---
title: "bluesky"
output: html_document
date: "2022-12-14"
---

## Setup

```{r}
library(hdi)
library(tidyverse)
library(rsq)
library(lme4)
```

```{r}
trainX <- read.csv('./data/clean_data/trainX.csv')
trainY <- read.csv('./data/clean_data/trainy.csv')
```


```{r}
all(trainX$MapBlkLot_Master == trainY$MapBlkLot_Master)
trainX <- select(trainX, -MapBlkLot_Master)
trainY <- select(trainY, -MapBlkLot_Master)
df <- cbind(trainX, trainY)
```



### EDA

```{r}
colnames(df)

ggplot(df) +
  geom_point(aes(x=YRBLT, y=Developed))

```

```{r}
range(df$YRBLT)
```

### Model fitting

Fit high dimensional multi-level effect model.

```{r}
mod <- glm(Developed ~ . - (ZONE + neighborhood + Residential_Dummy + district + RP1CLACDE + CONSTTYPE + EXEMPTYPE + general_use_code), family='binomial', df)
```

I should try using forward selection.
```{r}
summary(mod)
```

```{r}
rsq.kl(mod)
```

```{r}
mod2 <- glmer(Developed ~ . + (1 | RP1CLACDE) - (ZONE + neighborhood + Residential_Dummy + district + RP1CLACDE + CONSTTYPE + EXEMPTYPE + general_use_code), 
              family='binomial', 
              df)
```

```{r}
summary(mod2)
```

